allowBuilds:
  core-js: true
  esbuild: true
  msw: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - '@tanstack/react-router@1.170.10'
  - '@tanstack/react-start-client@1.168.7'
  - '@tanstack/react-start-rsc@0.1.16'
  - '@tanstack/react-start-server@1.167.12'
  - '@tanstack/react-start@1.168.17'
  - '@tanstack/router-core@1.171.8'
  - '@tanstack/router-generator@1.167.12'
  - '@tanstack/router-plugin@1.168.13'
  - '@tanstack/start-client-core@1.170.6'
  - '@tanstack/start-plugin-core@1.171.9'
  - '@tanstack/start-server-core@1.169.7'
  - '@tanstack/start-storage-context@1.167.10'
